### ISSUE TITLE
New assessment crashing when selecting a user

### ISSUE THREAD

**Issue by markash** [markash/threesixty#4]
2016-01-16T14:38:33.158907+00:00 app[web.1]: Jan 16, 2016 2:38:33 PM com.vaadin.server.DefaultErrorHandler doDefault
2016-01-16T14:38:33.158911+00:00 app[web.1]: SEVERE:
2016-01-16T14:38:33.158913+00:00 app[web.1]: com.vaadin.data.Property$ReadOnlyException
2016-01-16T14:38:33.158914+00:00 app[web.1]:    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:493)
2016-01-16T14:38:33.158916+00:00 app[web.1]:    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
2016-01-16T14:38:33.158917+00:00 app[web.1]:    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:691)
2016-01-16T14:38:33.158918+00:00 app[web.1]:    at com.vaadin.ui.AbstractSelect.select(AbstractSelect.java:1527)
2016-01-16T14:38:33.158920+00:00 app[web.1]:    at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
2016-01-16T14:38:33.158921+00:00 app[web.1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-01-16T14:38:33.158922+00:00 app[web.1]:    at java.lang.reflect.Method.invoke(Method.java:497)
2016-01-16T14:38:33.158922+00:00 app[web.1]:    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
2016-01-16T14:38:33.158923+00:00 app[web.1]:    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
2016-01-16T14:38:33.158933+00:00 app[web.1]:    at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1159)
2016-01-16T14:38:33.158933+00:00 app[web.1]:    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
2016-01-16T14:38:33.158932+00:00 app[web.1]:    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003)
2016-01-16T14:38:33.158934+00:00 app[web.1]:    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
2016-01-16T14:38:33.158935+00:00 app[web.1]:    at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:730)
2016-01-16T14:38:33.158936+00:00 app[web.1]:    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:603)
2016-01-16T14:38:33.158915+00:00 app[web.1]:    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:729)
2016-01-16T14:38:33.158937+00:00 app[web.1]:    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:422)
2016-01-16T14:38:33.158919+00:00 app[web.1]:    at za.co.yellowfire.threesixty.ui.view.rating.AssessmentEntityEditForm.onEmployeeSelected(AssessmentEntityEditForm.java:286)

**Comment by markash** [comment]
Fixed in commit https://github.com/markash/threesixty/commit/fc427de167081986f530484a69cbadd16792d11e
